#!/usr/bin/env python3
"""Generates placeholder 2bpp DMG tile data (gfx.h) for Meteor Survival.
Replace with real art (GBTD / png2asset) whenever you like - the tile
layout in meteor.c is all that matters:
  0..8  ship frames (angles 0..8, 0=up, 8=right)
  9     bullet
  10-13 large rock (TL, TR, BL, BR of a 16x16)
  14    medium rock
  15    small rock
  16-17 ship explosion fragments
"""
import math

def blank(w, h): return [[0] * w for _ in range(h)]

def line(g, x0, y0, x1, y1):
    h, w = len(g), len(g[0])
    steps = int(max(abs(x1 - x0), abs(y1 - y0)) * 2) + 1
    for i in range(steps + 1):
        t = i / steps
        x = int(math.floor(x0 + (x1 - x0) * t + 1e-6))
        y = int(math.floor(y0 + (y1 - y0) * t + 1e-6))
        if 0 <= x < w and 0 <= y < h: g[y][x] = 3

def poly(g, pts):
    for i in range(len(pts)):
        a, b = pts[i], pts[(i + 1) % len(pts)]
        line(g, a[0], a[1], b[0], b[1])

def tile_bytes(g, ox=0, oy=0):
    out = []
    for r in range(8):
        lo = hi = 0
        for c in range(8):
            v = g[oy + r][ox + c]
            lo = (lo << 1) | (v & 1)
            hi = (hi << 1) | ((v >> 1) & 1)
        out += [lo, hi]
    return out

def ship_frame(a):
    ang = math.radians(a * 11.25)
    def rot(px, py):  # point relative to centre, 0 deg = up
        return (4 + px * math.cos(ang) - py * math.sin(ang),
                4 + px * math.sin(ang) + py * math.cos(ang))
    g = blank(8, 8)
    nose, rl, rr, notch = rot(0, -3.6), rot(-2.8, 3.0), rot(2.8, 3.0), rot(0, 1.4)
    poly(g, [nose, rl, notch, rr])
    return g

def rock_pts(cx, cy, r, jitter):
    pts = []
    for i, j in enumerate(jitter):
        t = i * 2 * math.pi / len(jitter)
        pts.append((cx + math.cos(t) * r * j, cy + math.sin(t) * r * j))
    return pts

tiles = []
ship = []
for a in range(9): ship += tile_bytes(ship_frame(a))

misc = []
g = blank(8, 8)                                  # bullet: 2x2 dot in centre
for y in (3, 4):
    for x in (3, 4): g[y][x] = 3
misc += tile_bytes(g)

big = blank(16, 16)                              # large rock
poly(big, rock_pts(8, 8, 7.4, [1.0, .8, 1.0, .85, 1.0, .75, .95, .9, 1.0, .8]))
for oy in (0, 8):
    for ox in (0, 8): misc += tile_bytes(big, ox, oy)

g = blank(8, 8)                                  # medium rock
poly(g, rock_pts(4, 4, 3.6, [1.0, .8, 1.0, .85, 1.0, .8]))
misc += tile_bytes(g)

g = blank(8, 8)                                  # small rock
poly(g, rock_pts(4, 4, 2.0, [1.0, .85, 1.0, .85]))
misc += tile_bytes(g)

debris = []
# Two shards for the ship's explosion, in the same jagged style as the rocks --
# the ship comes apart into the same material. Different jitter per shard so
# the four fragments thrown out are not four copies of one shape.
g = blank(8, 8)
poly(g, rock_pts(4, 4, 2.6, [1.0, .6, .9, .7, 1.0]))
debris += tile_bytes(g)

g = blank(8, 8)
poly(g, rock_pts(4, 4, 2.2, [.7, 1.0, .65, .95, .8]))
debris += tile_bytes(g)

def emit(name, data):
    s = f"const unsigned char {name}[{len(data)}] = {{\n"
    for i in range(0, len(data), 16):
        s += "    " + ",".join(f"0x{b:02X}" for b in data[i:i+16]) + ",\n"
    return s + "};\n"

with open("gfx.h", "w") as f:
    f.write("// Generated by gen_gfx.py - placeholder art. Safe to replace.\n#pragma once\n")
    f.write(emit("ship_tiles", ship))
    f.write(emit("misc_tiles", misc))
    f.write(emit("debris_tiles", debris))
print("ok", len(ship) // 16, "ship tiles,", len(misc) // 16, "misc tiles,",
      len(debris) // 16, "debris tiles")
