# Meteor Survival build.
#   make          build meteor.gb  (GBDK if GBDK_HOME is set, else Docker)
#   make gfx      regenerate gfx.h from gen_gfx.py
#   make border   regenerate the SGB border from tools/mkborder.py
#   make probe    headless PyBoy check of the wave ramp (implies sym)
#   make usage    ROM/RAM headroom
#   make image    build the gbdk-dev Docker image used when GBDK_HOME is absent
#   make clean
#
# The gbdk-dev image is shared with the other GB projects; build it from
# ../GB-Protector/Dockerfile (`make -C ../GB-Protector image`) if it is missing.

GBDK_HOME ?= $(HOME)/gbdk

ifneq ($(wildcard $(GBDK_HOME)/bin/lcc),)
  RUN   :=
  LCC   := $(GBDK_HOME)/bin/lcc
  USAGE := $(GBDK_HOME)/bin/romusage
  P2A   := $(GBDK_HOME)/bin/png2asset
else
  # GBDK is not installed on this host, so run the toolchain out of the image.
  # lcc must be the FULL PATH: it is not on PATH inside gbdk-dev, and a bare
  # `lcc` fails with "executable file not found".
  # -u keeps build artefacts owned by the user rather than root.
  RUN   := docker run --rm -u $(shell id -u):$(shell id -g) -v "$(CURDIR)":/work -w /work gbdk-dev
  LCC   := /opt/gbdk/bin/lcc
  USAGE := /opt/gbdk/bin/romusage
  P2A   := /opt/gbdk/bin/png2asset
endif

# -Wm-yn : the title in the ROM header, so a flash cart names it
# -Wl-m  : the linker map
# -Wl-j  : NoICE symbols, for emulator debuggers
# -Wm-ys : the Super Game Boy flag. WITHOUT IT THE BORDER SILENTLY NEVER
#          APPEARS: the SGB discards the border packets and behaves as a plain
#          DMG, so there is no error and nothing to see in mGBA either.
CFLAGS = -Wm-ys -Wm-yn"METEORSURV" -Wl-m -Wl-j

# sgb_border.c moves the border by rendering it; border_data.c is the art,
# generated by `make border` and committed like gfx.h so `make` needs no Python.
# It carries `#pragma bank 1`, keeping ~4 KB of tiles out of bank 0 -- this ROM
# is 32 KB and never switches banks, so bank 1 stays mapped for the whole run.
CFILES = meteor.c sgb_border.c border_data.c

# gfx.h and border_data.h are on the line deliberately: they are GENERATED, and
# a make that does not know that says "nothing to do" after `make gfx` or
# `make border`, leaving the OLD ROM in place.
meteor.gb: $(CFILES) gfx.h sgb_border.h border_data.h
	$(RUN) $(LCC) $(CFLAGS) -o $@ $(CFILES)

# A `-debug` build: the linker map then carries EVERY symbol, not just the
# globals, which is what emulator debuggers want. Bigger ROM, so not the default.
# Phony, so it always re-links: as a file target make would see meteor.gb already
# newer than its sources and leave the release ROM behind.
sym: $(CFILES) gfx.h sgb_border.h border_data.h
	$(RUN) $(LCC) $(CFLAGS) -debug -o meteor.gb $(CFILES)

# PyBoy lives in a venv, not on PATH (and not in this repo), so fall back to
# the one GB-Protector keeps:   make probe PY=python3
PY ?= $(firstword $(wildcard .venv/bin/python ../GB-Protector/.venv/bin/python) python3)

# Headless check of the wave ramp. Needs the -debug ROM, because the probe reads
# the game's own statics (wave, rocks) by address out of meteor.noi -- a release
# build's map has no statics. Dev-only; nothing in the build depends on it.
probe: sym
	$(PY) tools/probe_ramp.py meteor.gb

# Regenerate placeholder art (or replace gfx.h with your own tiles, same layout)
gfx:
	python3 gen_gfx.py

# The Super Game Boy border: tools/mkborder.py draws art/border_sgb.png (256x224,
# with the 160x144 game area at x=48,y=40 transparent), and png2asset packs it
# for sgb_border.c. Both the PNG and border_data.c are committed, so this only
# needs running when the art changes. `-b 1` is the `#pragma bank 1` above.
# mkborder.py asserts the two things the transfer punishes -- a palette over 16
# colours, art inside the window, and a tile count of exactly 128.
border:
	python3 tools/mkborder.py
	$(RUN) $(P2A) art/border_sgb.png -map -bpp 4 -max_palettes 4 \
	      -pack_mode sgb -use_map_attributes -b 1 -c border_data.c

usage: meteor.gb
	$(RUN) $(USAGE) meteor.map -g

image:
	docker build -t gbdk-dev .

clean:
	rm -f meteor.gb *.lst *.map *.sym *.noi *.asm *.ihx *.o *.rel *.adb *.cdb

.PHONY: all sym probe gfx border usage image clean

all: meteor.gb
